### PR TITLE
Add OpenMP compile / link flags to the toast_test and toast_mpi_test executables

### PR DESCRIPTION
**Pull request by tskisner**
@keskitalo, does this fix the pragma warnings you were seeing?

### CODE REVIEW

**Comment by keskitalo** [comment]
I am still seeing the issue:
```
[ 50%] Building CXX object src/libtoast/CMakeFiles/toast.dir/toast.cpp.o
cd /global/homes/k/keskital/software/cori/git/toast/build/src/libtoast && /opt/cray/pe/craype/2.5.18/bin/CC   -I/global/homes/k/keskital/software/cori/git/toast/src/libtoast/include -I/global/home\
s/k/keskital/software/cori/git/toast/src/libtoast/gtest/googletest/include -I/global/common/software/cmb/cori/cmbenv-intel_20190806/cmbenv_aux/include  -O3 -g -fPIC -xcore-avx2 -axmic-avx512 -pthr\
ead -std=c++14 -O3 -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/toast.dir/toast.cpp.o -c /global/homes/k/keskital/software/cori/git/toast/src/libtoast/toast.cpp
In file included from /global/homes/k/keskital/software/cori/git/toast/src/libtoast/include/toast.hpp(19),
                 from /global/homes/k/keskital/software/cori/git/toast/src/libtoast/toast.cpp(6):
/global/homes/k/keskital/software/cori/git/toast/src/libtoast/include/toast/tod_mapscan.hpp(21): warning #3180: unrecognized OpenMP #pragma
      #pragma \
      ^

In file included from /global/homes/k/keskital/software/cori/git/toast/src/libtoast/include/toast.hpp(19),
                 from /global/homes/k/keskital/software/cori/git/toast/src/libtoast/toast.cpp(6):
/global/homes/k/keskital/software/cori/git/toast/src/libtoast/include/toast/tod_mapscan.hpp(42): warning #3180: unrecognized OpenMP #pragma
      #pragma omp parallel for
      ^
```
and
```
[ 65%] Building CXX object src/libtoast_mpi/CMakeFiles/toast_mpi.dir/toast_mpi.cpp.o
cd /global/homes/k/keskital/software/cori/git/toast/build/src/libtoast_mpi && /opt/cray/pe/craype/2.5.18/bin/CC   -I/global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/../libtoast/in\
clude -I/global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/include -I/global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi -I/global/common/software/cmb/cori/cmbenv-inte\
l_20190806/cmbenv_aux/include -I/global/homes/k/keskital/software/cori/git/toast/src/libtoast/include -I/global/homes/k/keskital/software/cori/git/toast/src/libtoast/gtest/googletest/include  -O3 \
-g -fPIC -xcore-avx2 -axmic-avx512 -pthread -std=c++14 -O3 -DNDEBUG -fPIC   -std=gnu++11 -o CMakeFiles/toast_mpi.dir/toast_mpi.cpp.o -c /global/homes/k/keskital/software/cori/git/toast/src/libtoas\
t_mpi/toast_mpi.cpp
In file included from /global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/../libtoast/include/toast.hpp(19),
                 from /global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/include/toast_mpi.hpp(11),
                 from /global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/toast_mpi.cpp(6):
/global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/../libtoast/include/toast/tod_mapscan.hpp(21): warning #3180: unrecognized OpenMP #pragma
      #pragma \
      ^

In file included from /global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/../libtoast/include/toast.hpp(19),
                 from /global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/include/toast_mpi.hpp(11),
                 from /global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/toast_mpi.cpp(6):
/global/homes/k/keskital/software/cori/git/toast/src/libtoast_mpi/../libtoast/include/toast/tod_mapscan.hpp(42): warning #3180: unrecognized OpenMP #pragma
      #pragma omp parallel for
      ^
```

**Comment by tskisner** [comment]
Ok, it looks like that is a different problem- the intel "-qopenmp" flag should have been detected and appear in those lines.  I'll test on cori.

**Comment by tskisner** [comment]
I don't see this on cori.  Steps that I did:
```
module use /global/common/software/cmb/cori/cmbenv-intel_20190806/modulefiles
module load cmbenv
source cmbenv
cd toast
cd build; rm -rf *
../platforms/cori-intel.sh
make -j 4
```
No warnings and I see "-qopenmp" in all the compile / link lines.  Are you using gcc or intel on cori?

**Comment by keskitalo** [comment]
This is with Intel.

My environment is set up with:
```
      module use /global/common/software/cmb/cori/cmbenv-intel_20190806/modulefiles
      module load cmbenv
      source cmbenv
      export PS1="${RED}${REVERSE}[cmbenv]${CLEAR} $(ppwd \l)\h:\W> "
      export PREFIX=/global/cscratch1/sd/keskital/software-cmbenv
      export PYTHONPATH=$PREFIX/lib/python3.6/site-packages:$PYTHONPATH
      export CC=icc
      export CXX=icpc
      export F77=ifort
      export FC=ifort
      export MPICC=cc
      export MPIFC=ftn
      export MPICXX=CC
      export OPENMP_CFLAGS="-qopenmp"
      export OPENMP_FCFLAGS="-qopenmp"
      export OPENMP_CXXFLAGS="-qopenmp"
      export CFLAGS="-O3 -g -fPIC -xcore-avx2 -axmic-avx512 -pthread -std=gnu99"
      export FCFLAGS="-O3 -g -fPIC -xcore-avx2 -axmic-avx512 -pthread -heap-arrays 16"
      export CXXFLAGS="-O3 -g -fPIC -xcore-avx2 -axmic-avx512 -pthread -std=c++14"
      export PATH=$PREFIX/bin:$PATH
      export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH
      export LDSHARED="icc -shared"
```
and I see the warning even when running your platform file, `platforms/cori-intel.sh`.
I definitely have the HEAD of `cmfix`.

**Comment by tskisner** [comment]
OK, I actually had those same warnings in my build and did not notice them.  The latest push fixes those in my cori build.  Hopefully they are now gone for you as well.

**Comment by keskitalo** [comment]
I confirm that the latest commit fixes the warning.

**Comment by tskisner** [comment]
The travis failures are due to a transient apt-get problem.  Merging

**Pull request merged**
