### PR TITLE
Move custom utils from pipelines into the library

### PR DESCRIPTION
**Pull request by zonca**
I am preparing my work on configuration files.

I think it would be easier if first I simplify a bit the pipeline scripts.
So as suggested some time ago by @tskisner I would like to move some of the custom utility functions into the TOAST library.

I just started from one and I'd like some feedback before I go ahead. Is this ok? Is `toast.Data` the right place for functionality related to looping through observations?

### CODE REVIEW

**Comment by tskisner** [comment]
I think this is the right direction @zonca, and I see you are also working towards addressing #97, which is great!  Let's see what feedback @keskitalo has.

**Comment by zonca** [comment]
I have a suggestion:
what about I create a new thin object that holds no data, but it is just a reference to all of the TOD objects then we implement `__add__` and `__mult__` and so on:

```
class TODReference:
    def __init__(self, data, key):
        self.data = data
        self.key = key
    def __add__(self, other):
        for ob in self.data.obs:
            # loop through dets
                 #sum tod of self.key and other.key
        
toast.Data["signal"] returns a TODReference with the "signal" key.

# So I can do:

toast.Data["total"] = toast.Data["signal"] + toast.Data["dipole"]

```

**Comment by zonca** [comment]
what about my suggestion of implementing `TODReference`? Otherwise let me know asap and I'll just copy over @keskitalo's code and tweak it a bit.

**Comment by tskisner** [comment]
I have no preference here.  Whatever you both think would work best.

**Comment by zonca** [comment]
@keskitalo what about my suggestion of implementing `TODReference`? Otherwise let me know asap and I'll just copy over your code and tweak it a bit.

**Comment by keskitalo** [comment]
I like it. A nice way of implementing TOD arithmetic. We'll want scalar multiplication as well.

**Pull request closed without merging**
