### PR TITLE
By default, do not flag the pointing matrix samples.  

### PR DESCRIPTION
**Pull request by tskisner**
Calling code can enable flagging of pointing matrix elements at construction time, using a bit mask applied to the common TOD flags.

### CODE REVIEW

**Comment by keskitalo** [comment]
Should there be a keyword to allow retrieving the common flags from the cache?

**Comment by tskisner** [comment]
I guess I had never thought of that, and had just assumed that the TOD class for a particular experiment would return common flags based on housekeeping and other data.  However, I guess if the calculation of the common flags is external to the TOD class, then those flags might exist only in the cache.

If that is the typical scenario, then it seems to call into question the design of the TOD class.  What exactly should be provided only by the TOD class (and never in the cache)?  Just raw data from the data acquisition system?  For example, one could treat the pointing as some kind of "processed output" that is the result of using raw sensor data.

I will add another keyword for now, but we should seriously consider what we want the TOD class to return.  Maybe it should literally just return raw data at various sample rates and that is it.  Then we would have operators that produced pointing and other products in the cache.

**Comment by tskisner** [comment]
Does that latest commit address your request for using cached flags?

**Comment by keskitalo** [comment]
Yes they do! Merged.

**Pull request merged**
