### PR TITLE
Bugfix satellite sim

### PR DESCRIPTION
**Pull request by zonca**
As I was working on PICO simulations, I found some bugs in `toast_satellite_sim.py` or PySM-related.

Do not merge now, I'll ask for review once PICO sims are done.

### CODE REVIEW

**Comment by zonca** [comment]
need to update the unit tests

**Comment by zonca** [comment]
removed the ground tests from Travis

**Comment by zonca** [comment]
@tskisner this is ready to review, there are a few bugfixes on the satellite sim pipeline and a test on Travis about it.
I'll implement also the ground tests later, see #234 

If it is useful I can merge all the last 8 commits into 1 (it implements the examples running on Travis).

**Comment by tskisner** [comment]
Hello @zonca , these all look good, merge when ready.

**Comment by zonca** [comment]
thanks @tskisner it is completed and ready to merge, unless you want me to squash the last 8 commits.

**Pull request merged**
