### PR TITLE
create new package todmap for pysm operator

### PR DESCRIPTION
**Pull request by zonca**
@keskitalo is this ok to address #200?

do you have a better suggestion for the name of the package?
I used `scan` because the operator scans a map domain object to a TOD.

### CODE REVIEW

**Comment by zonca** [comment]
I have some trouble installing the new package. @tskisner can you please point me (I might have asked it already) to where do I tell the build system to install other files?

Is there a spot in the docs I can add this so I can stop asking it?

**Comment by keskitalo** [comment]
@zonca this works for me. Although the name could be something more generic so we can add other operators that depend on `map` and `tod` later on. @tskisner what do you think about `todmap`?

**Comment by tskisner** [comment]
@keskitalo , todmap is a fine suggestion.  Then we can move the other stuff in sim_det_map.py into that new subpackage.  @zonca, for the build system, the new directory needs to be added to src/python/CMakeLists.txt and also src/python/Makefile.am (in subdirs at the top).  Then the new directory needs a Makefile.am (copy the one from the tod subdirectory).  Add that new directory to the top-level configure.ac.

I'm happy to make the necessary build system changes if you push your branch to hpc4cmb/toast.  Then we can open a new pull request from their against master.  The build system will be made simpler soon.

**Comment by zonca** [comment]
ok, renamed to `todmap`,
@tskisner I tried to add to the build system but didn't work, it gives "no target install" error.
Every time I submit a PR, I tick the "allow edit from maintainers" box so you have push access to my branch.

**Comment by zonca** [comment]
actually maybe I fixed it, I had forgot the changes in `configure.ac`, retesting now

**Comment by zonca** [comment]
ok, I think I fixed it, once Travis passes, this is ready to merge

**Comment by keskitalo** [comment]
@zonca the tests seem to fail because they cannot import `OpSimPySM`. Perhaps they are still looking for it in the old location?

It is easy to run the tests on your own system with `'python3 -c "import toast.tests; toast.tests.run()"'`. This way you don't have to wait for Travis.

**Comment by zonca** [comment]
thanks @keskitalo fixed now

**Comment by keskitalo** [comment]
Looks great. I'll merge.

**Pull request merged**
