### PR TITLE
Fix PySM operator polarization change of coordinate system

### PR DESCRIPTION
**Pull request by zonca**
Addresses #242

### CODE REVIEW

**Comment by zonca** [comment]
* I modified the `check_maps.py` script to check also polarization
* I updated the expected outputs for satellite
* `satellite` test is passing on my machine
* I probably need to update also the ground results, but better first wait for the issue caused by #240 to be sorted out.

**Comment by zonca** [comment]
restarted build to check if it picks up `healpy` 1.12

**Comment by zonca** [comment]
this is complete and ready for review
I also updated the pipelines tests, they also compare polarization.
This branch requires healpy 1.12.3 for the polarization rotation to work correctly.

**Comment by ziotom78** [comment]
Andrea, I tested a bit `rotate_alm` and find that there are cases where it would be more useful than `Rotator.rotate_map`, as it properly preserves CMB TT/EE/BB spectra. What do you think about something like this:

```python
if self.comm.rank == 0 and self.coord != "G":
    # PySM is always in Galactic, make rotation to Ecliptic or Equatorial
    angles = hp.rotator.coordsys2euler_zyz(coord = ["G", self.coord])
    alms = hp.map2alm(full_map_rank0)
    hp.rotate_alm(alms, *angles)
    full_map_rank0 = hp.alm2map(alms, nside)
```

In this way one would preserve the shape of C_l spectra even in other coordinate systems. (Compare this with the [E/B mode mixing](https://github.com/healpy/healpy/issues/460) caused by `healpy.Rotator.rotate_map`.)

**Comment by tskisner** [comment]
Did we ever resolve the conflict that @keskitalo saw with healpy 1.12 and the stand-alone libsharp plus python bindings?  I believe his use case was that he already had libsharp installed and then installed healpy 1.12 to the same prefix, leading it to try and link to the existing libsharp.  The libsharp bundled with healpy is newer / different than the stand-alone version.

**Comment by tskisner** [comment]
If our PySM code requires both healpy-1.12 and libsharp, and it is impossible to install those simultaneously, then...  Isn't that a problem?  Or are you saying that installing first healpy then libsharp into a new installation prefix will work?  It seems like a mess, but I agree that it is something that needs to be sorted out upstream of toast.

It does not have to hold up this PR- I'll separately go try to install latest healpy / libsharp in our NERSC dependency stack.

**Comment by zonca** [comment]
@tskisner this is ready to merge

**Comment by tskisner** [comment]
Looks fine to me, merge away.

**Pull request merged**
