### PR TITLE
[WIP] Run ground examples on Travis

### PR DESCRIPTION
**Pull request by zonca**
splitted from #228 in order to implement #221 

#228 adds Travis-CI examples just on satellite, ground examples require more work.
once #228 is merged this will be just a few commits.

### CODE REVIEW

**Comment by zonca** [comment]
@keskitalo ground is working!!
@tskisner this is ready to review

**Comment by tskisner** [comment]
This looks good to me.  Go ahead and merge when you are ready.

**Comment by zonca** [comment]
I don't have the powers!

**Comment by tskisner** [comment]
I just changed that, but will merge this right away :-)

**Pull request merged**
