### PR TITLE
Improve OpenMP use

### PR DESCRIPTION
**Pull request by tskisner**
This work includes:

- Upgrade bundled pybind11
- Improve cmake checks for OpenMP to include checks for target offload
- Port the previous prototype OpenACC code to use OpenMP.  Disabled by default.
- For several operators, move the loops over views / detectors into the compiled code
- Make the OpenMP code as similar as possible between CPU / Target use
- Change to definition of an "Interval" to be simply a C struct that corresponds to a numpy dtype.  This greatly simplifies the passing of intervals / views between python and C++, and should also help performance in other ways.  `IntervalList` now simply becomes a numpy array.

### CODE REVIEW

**Comment by tskisner** [comment]
Ok, the test runner now fails correctly.  Next to debug the underlying problem.

**Comment by tskisner** [comment]
This PR is ready, but I am going to do some larger integration tests on cori just to double check that nothing has broken.  Any changes from those tests should be extremely minor.

**Review by nestordemeure — APPROVED** [review]
That is *long* PR but I saw nothing chocking and I have used part of it in another branch.

**Comment by nestordemeure** [comment]
One of the tests fails for me (Perlmutter GPU, single node):

```
test_lhs (toast.tests.ops_mapmaker_solve.MapmakerSolveTest) ... TOAST WARNING: Mission start time '2023-02-23 00:00:00' is not timezone-aware.  Assuming UTC.
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
Proc 0:   File "/pscratch/sd/n/nestor/toast/toast_build/lib/python3.9/site-packages/toast/tests/ops_mapmaker_solve.py", line 261, in test_lhs
    np.testing.assert_allclose(
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
Proc 0: AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 22 / 22 (100%)
Max absolute difference: 14915213.38488667
Max relative difference: 2.94823249
 x: array([ -2416732.095875,  -3249640.95268 ,   3135108.226578,
         5945331.217506,  -8840219.391378,   7396425.352478,
        15894176.926187,  -3736534.544713,  -5763051.228605,...
 y: array([  -612104.809709,  -6708886.753274,   3410117.720138,
         8524760.685426, -14581368.858271,   8281146.744278,
        22677814.921668,  -5053496.240713,  -3380968.443352,...

[0]fail MPICH ERROR [Rank 0] [job id ] [Tue May 24 12:42:08 2022] [nid001889] - Abort(1) (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Comment by nestordemeure** [comment]
I found  another failing test:

```shell
test_compare (toast.tests.template_offset.TemplateOffsetTest) ... TOAST WARNING: Mission start time '2023-02-23 00:00:00' is not timezone-aware.  Assuming UTC.
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|==================================================================================================================================| 1.3k/1.3k (100.00%)         0s
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
Proc 0:   File "/pscratch/sd/n/nestor/toast/toast_build/lib/python3.9/site-packages/toast/tests/template_offset.py", line 158, in test_compare
    np.testing.assert_allclose(amps.local, pyamps.local)
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
Proc 0:   File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
Proc 0: AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 22 / 22 (100%)
Max absolute difference: 562.
Max relative difference: 0.95093063
 x: array([ 54.,  57.,  69.,  36.,  46.,  65.,  50.,  29.,  80.,  70.,  47.,
        93.,  70.,  63.,  49.,  84.,  91., 116.,  72.,  76.,  76.,  38.])
 y: array([591., 591., 591., 591., 591., 591., 591., 591., 591., 591., 101.,
       591., 591., 591., 591., 591., 591., 591., 591., 591., 591., 101.])

fail 

======================================================================
FAIL: test_compare (toast.tests.template_offset.TemplateOffsetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pscratch/sd/n/nestor/toast/toast_build/lib/python3.9/site-packages/toast/tests/template_offset.py", line 158, in test_compare
    np.testing.assert_allclose(amps.local, pyamps.local)
  File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/global/u2/n/nestor/hackathon_perlmutter/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 22 / 22 (100%)
Max absolute difference: 562.
Max relative difference: 0.95093063
 x: array([ 54.,  57.,  69.,  36.,  46.,  65.,  50.,  29.,  80.,  70.,  47.,
        93.,  70.,  63.,  49.,  84.,  91., 116.,  72.,  76.,  76.,  38.])
 y: array([591., 591., 591., 591., 591., 591., 591., 591., 591., 591., 101.,
       591., 591., 591., 591., 591., 591., 591., 591., 591., 591., 101.])

----------------------------------------------------------------------
Ran 1 test in 0.753s

FAILED (failures=1)
```

**Comment by tskisner** [comment]
I am not seeing this failure @nestordemeure .  Here are the build / run steps that work for me running on a perlmutter gpu node (without actually using the gpus).  For anyone reading this, there is a known issue running on the cpu nodes that we are still working on.

Load dependencies:
```
module use /global/common/software/cmb/perlmutter/default/modulefiles
module load cmbenv
source cmbenv
```
Checkout branch:
```
cd git/toast
git fetch
checkout -b omp_target -t origin/omp_target
```
Build using the included platform config:
```
mkdir build
cd build
../platforms/perlmutter-gcc.sh -DCMAKE_INSTALL_PREFIX=$SCRATCH/toast_omp
make -j 4 install
```
Load the install prefix into environment:
```
export PATH=${SCRATCH}/toast_omp/bin:${PATH}
export PYTHONPATH=${SCRATCH}/toast_omp/lib/python3.9/site-packages:${PYTHONPATH}
```
Make a test directory:
```
cd $SCRATCH
mkdir test
cd test
```
Run on one interactive node:
```
salloc -N 1 -C gpu --gpus 1 -A mp107_g --qos=interactive -t 01:00:00
```
Launch unit tests on one process:
```
OMP_NUM_THREADS=2 srun -N 1 -n 1 python -c 'import toast.tests; toast.tests.run()'
```
I also ran with 4 processes  (`-n 2`) and this passed as well.

**Comment by nestordemeure** [comment]
@tskisner interesting, it fails when I omit `OMP_NUM_THREADS=2`.

This also fails: `OMP_NUM_THREADS=4 python -c 'import toast.tests; toast.tests.run("template_offset"); toast.tests.run("ops_mapmaker_solve"); toast.tests.run("ops_mapmaker")'`

**Comment by tskisner** [comment]
I am still not seeing this...  Let's touch base on slack to see if our environments are the same.  Using the same software-loading commands I pasted above, I get:

Test on one compute node:
```
$> salloc -N 1 -C gpu --gpus 1 -A mp107_g --qos=interactive -t 01:00:00
salloc: Pending job allocation 2240489
salloc: job 2240489 queued and waiting for resources
salloc: job 2240489 has been allocated resources
salloc: Granted job allocation 2240489
salloc: Waiting for resource configuration
salloc: Nodes nid002552 are ready for job

# Run with one MPI process (i.e. COMM_WORLD not None)
$> OMP_NUM_THREADS=4 srun -N 1 -n 1 python -c 'import toast.tests; toast.tests.run()'
<snip>
----------------------------------------------------------------------
Ran 171 tests in 464.638s
[0] OK

# Explicitly disable use of MPI (i.e. COMM_WORLD is None)
$> OMP_NUM_THREADS=4 MPI_DISABLE=1 srun -N 1 -n 1 python -c 'import toast.tests; toast.tests.run()'
<snip>
----------------------------------------------------------------------
Ran 171 tests in 340.625s
OK

# Run with two MPI processes
$> OMP_NUM_THREADS=4 srun -N 1 -n 2 python -c 'import toast.tests; toast.tests.run()'
<snip>
----------------------------------------------------------------------
Ran 171 tests in 321.233s
[0] OK
[1] OK
```

Test on a login node (MPI is always disabled on the login nodes):
```
$> OMP_NUM_THREADS=4 python -c 'import toast.tests; toast.tests.run()'
<snip>
----------------------------------------------------------------------
Ran 171 tests in 417.617s
OK
```

**Comment by tskisner** [comment]
@nestordemeure and I tracked down our differences to threading concurrency (it would only fail at higher concurrency).  I just pushed a commit that fixes one data race and one incorrect use of OpenMP reduction on a dynamically allocated array.  This test in question now passes for OMP_NUM_THREADS from 1 to 32.

**Pull request merged**
