### PR TITLE
Observe elevation limits in SSO scheduling

### PR DESCRIPTION
**Pull request by keskitalo**
Companion PR for #408.

### CODE REVIEW

**Comment by keskitalo** [comment]
Forgot this wasn't already merged. Should be non-controversial, addressing issues found in SO work.

**Review by tskisner — APPROVED** [review]
Thanks for this change.  Does this also effectively port #376 changes?  If so, I'll mark it off the 3.0 task list.

**Comment by keskitalo** [comment]
This PR does not include the fixes from #376. I'll file another PR to handle those shortly.

**Comment by keskitalo** [comment]
@tskisner I misread. This PR does include fixes from #376. Please go ahead and cross it off the 3.0 task list.

**Pull request merged**
